In [1]:
import pandas as pd
df = pd.read_csv('youtube_link2.csv', index_col=0)
df.head(5)

,video_title,url,video_id,channel_id,channel_title,category,publishedAt,view_count,description,publishedAt_week,play_time,tags_split,tags_len
0,횡성 38년전통 광암막국수🍜 전메뉴 먹방,https://www.youtube.com/watch?v=rqwXDBojRpY,rqwXDBojRpY,UCfpaSruWW3S4dibonKXENjA,tzuyang쯔양,22,2021-06-08,2270642,1,Tuesday,770,"['大食い', 'real sound', '리얼사운드', 'social eating'...",14
1,줄서서 먹는 철원 60년 전통 막국수! 전메뉴 먹방(Feat.철원 소방서) Kore...,https://www.youtube.com/watch?v=bC711I-IPck,bC711I-IPck,UCfpaSruWW3S4dibonKXENjA,tzuyang쯔양,22,2020-11-25,2341315,0,Wednesday,990,"['大食い', 'real sound', '리얼사운드', 'social eating'...",7
3,200년 전통! 줄서서 먹는 만두 72개만 먹방 Korean mukbang eati...,https://www.youtube.com/watch?v=GGQrROGsuuw,GGQrROGsuuw,UCfpaSruWW3S4dibonKXENjA,tzuyang쯔양,22,2020-11-25,1698478,0,Wednesday,844,"['大食い', 'real sound', '리얼사운드', 'social eating'...",7
4,소고기 5가지 부위 3kg 먹방,https://www.youtube.com/watch?v=B3PH-TLulNk,B3PH-TLulNk,UCfpaSruWW3S4dibonKXENjA,tzuyang쯔양,22,2020-12-07,4185351,0,Monday,1046,"['大食い', 'real sound', '리얼사운드', 'social eating'...",13
5,[골라봐야지] 무도 멤버는 예능을 찢어~ 그만큼 신나신 딜탱서포터종이인형｜아는형님｜...,https://www.youtube.com/watch?v=0eXtafeDxvc,0eXtafeDxvc,UCF3UEVPt5zZTlBVJwDG317g,JTBC Voyage,24,2021-04-20,1779084,1,Tuesday,640,"['정형돈', '정준하', '하하', 'HAHA', '광희', '무한도전', 'in...",38

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5750 entries, 0 to 16416
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   video_title       5750 non-null   object
 1   url               5750 non-null   object
 2   video_id          5750 non-null   object
 3   channel_id        5750 non-null   object
 4   channel_title     5750 non-null   object
 5   category          5750 non-null   object
 6   publishedAt       5750 non-null   object
 7   view_count        5750 non-null   int64
 8   description       5750 non-null   int64
 9   publishedAt_week  5750 non-null   object
 10  play_time         5750 non-null   int64
 11  tags_split        5750 non-null   object
 12  tags_len          5750 non-null   int64
dtypes: int64(4), object(9)
memory usage: 628.9+ KB

In [3]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys
import time
import re

likes8=[]
unlikes8=[]
comments8=[]

options = webdriver.ChromeOptions()
options.add_argument("disable-gpu")

for i in range(20):
    driver = Chrome()
    driver.implicitly_wait(2)
    driver.get(df["url"].iloc[2202+i])

    body=driver.find_element_by_tag_name('body')
    num=2
    while num:
        body.send_keys(Keys.PAGE_DOWN)
        time.sleep(1.5)
        num -= 1
    time.sleep(2)
    html = driver.page_source
    soup = BeautifulSoup(html, 'lxml')
    
    try:
        like=soup.find('yt-formatted-string',{'id':'text','class':'style-scope ytd-toggle-button-renderer style-text'})['aria-label'].split("좋아요 ")[1]
        like=like.replace(',', '')
        likes8.append(like)
    except:
        likes8.append(0)    
        
    try:
        unlike=soup.find_all('yt-formatted-string',{'id':'text','class':'style-scope ytd-toggle-button-renderer style-text'})[1]['aria-label'].split("싫어요 ")[1]
        unlike=unlike.replace(',', '')
        unlikes8.append(unlike)
    except:
        unlikes8.append(0)      
    
    try:   
        comment=soup.find('ytd-comments', {'id' : 'comments'}).find('yt-formatted-string', 'count-text style-scope ytd-comments-header-renderer').text.split("댓글 ")[1]
        comment=comment.replace(',', '')
        comments8.append(comment)
    except:
        comments8.append(0)   
        
    driver.close()

In [4]:
df["url"].iloc[4517+1232]

'https://www.youtube.com/watch?v=Y2KZuq4YKuE'

In [6]:
data = {'likes': likes8, 'unlikes': unlikes8,'comments': comments8}
df8 = pd.DataFrame(data)
df8

     likes unlikes comments
0     369개     16개      47개
1     146개      4개       9개
2     267개     17개      25개
3     279개      3개       3개
4     172개      8개      17개
5     371개     18개     117개
6     145개      4개       4개
7     262개      3개      12개
8     221개      6개      28개
9     304개     14개      21개
10    430개     16개      40개
11       0       0        0
12    275개      8개      50개
13    414개     25개        0
14   1315개    117개      82개
15    788개     31개      84개
16    558개     18개      60개
17    199개      5개       7개
18    123개      2개       6개
19  11309개    259개     402개

In [7]:
df8.to_csv("youtube_df8.csv")